### PR TITLE
Added Typescript based version of both the Full and Starter Projects

### PR DESCRIPTION
**Pull request by colindekker**
Typescript 2.5.3 compiled based replica of original Babel based code. split up the files under Dashboard into easier maintainable separate files.

### CODE REVIEW

**Comment by kaminskypavel** [comment]
any chance ts merge will be approved?

**Comment by naster01** [comment]
Can you adapt it to V2? Thx!

**Comment by plotka** [comment]
Can this be merged?

**Comment by xidedix** [comment]
@plotka 
This pr is for obsolete v1 of CoreUI, not the latest.

**Comment by xidedix** [comment]
no longer relevant

**Comment by plotka** [comment]
@xidedix  Ok, are there plans for adding typings for the current version?

**Comment by xidedix** [comment]
The incoming CoreUI v3 for React will include typings by default.

**Pull request closed without merging**
