### PR TITLE
Adding clicking outside of sidebar or aside on mobile closes the sidebar

### PR DESCRIPTION
**Pull request by JamesSingleton**
This takes care of https://github.com/coreui/coreui-free-react-admin-template/issues/74

### CODE REVIEW

**Comment by JamesSingleton** [comment]
@xidedix any update on this getting merged?

**Comment by xidedix** [comment]
hi @JamesSingleton 
Thanks for PR, I like your solution, it simply works. Just wondering if we can do it in React way and make Sidebar component aware of outside clicks. It is possible but requires some more code.

**Comment by JamesSingleton** [comment]
Hi @xidedix ,

Thanks for your reply/ input, I will look it over this weekend and make another pull request.

**Comment by JamesSingleton** [comment]
@xidedix so do you want me to make the changes in this repo then? https://github.com/coreui/coreui-react then?

**Comment by xidedix** [comment]
@JamesSingleton 
https://github.com/coreui/coreui-react is the place

**Comment by JamesSingleton** [comment]
Awesome, thank you. I will take a look at it this weekend.

**Comment by xidedix** [comment]
solved with `@coreui/react ^2.0.5` and up

**Pull request closed without merging**
